name: 'Terraform Deploy'

on:
  push:
    branches: [ "main" ]
  pull_request:

permissions:
  contents: read

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout el repo
    - name: Checkout
      uses: actions/checkout@v4

    # 2. Login en Azure usando los secrets
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: |
          {
            "clientId": "${{ secrets.TF_CLIENT_ID }}",
            "clientSecret": "${{ secrets.TF_CLIENT_SECRET }}",
            "subscriptionId": "${{ secrets.TF_SUBSCRIPTION_ID }}",
            "tenantId": "${{ secrets.TF_TENANT_ID }}"
          }

    # 3. Instalar Terraform
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.9.5   # puedes ajustar la versión si quieres

    # 4. Inicializar Terraform
    - name: Terraform Init
      run: terraform init

    # 5. Validar que la sintaxis es correcta
    - name: Terraform Validate
      run: terraform validate

    # 6. Plan de ejecución
    - name: Terraform Plan
      run: terraform plan -input=false

    # 7. Aplicar cambios (solo cuando haces push a main)
    - name: Terraform Apply
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: terraform apply -auto-approve -input=false
