name: 'Terraform Azure Deploy'

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.5  # usa la versión que prefieras

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.TF_CLIENT_ID }}
          tenant-id: ${{ secrets.TF_TENANT_ID }}
          subscription-id: ${{ secrets.TF_SUBSCRIPTION_ID }}
          client-secret: ${{ secrets.TF_CLIENT_SECRET }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -input=false

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply -auto-approve -input=false
